#!/bin/bash
set -Eeuo pipefail

cd "$(dirname "$(readlink -f "$BASH_SOURCE")")"

# Check prerequisites
if ! command -v jq &> /dev/null; then
    echo "Error: jq is required but not installed."
    exit 1
fi

if [ ! -f versions.json ]; then
    echo "Error: versions.json not found in $(pwd)"
    exit 1
fi

autogenerated='NOTE: THIS DOCKERFILE IS GENERATED VIA "apply-templates.sh"! PLEASE DO NOT EDIT IT DIRECTLY.'

generated=()

# Iterate over each version entry in versions.json
# Expected structure:
# {
#   "<pg_version>-<postgis_version>": {
#     "<variant>": {
#       "template": "Dockerfile.template" | "Dockerfile.alpine.template" | "Dockerfile.master.template",
#       "PG_MAJOR": "17",
#       "POSTGIS_MAJOR": "3",
#       "POSTGIS_VERSION": "3.5.2+dfsg-1.pgdg110+1",
#       "POSTGIS_SHA256": "abc123...",
#       "BOOST_VERSION": "1.74.0",
#       "POSTGIS_GIT_HASH": "...",
#       "CGAL_GIT_HASH": "...",
#       "SFCGAL_GIT_HASH": "...",
#       "PROJ_GIT_HASH": "...",
#       "GDAL_GIT_HASH": "...",
#       "GEOS_GIT_HASH": "...",
#       "tags": "postgis/postgis:17-3.5, ..."
#     }
#   }
# }

for version in $(jq -r 'keys[]' versions.json); do
    for variant in $(jq -r --arg v "$version" '.[$v] | keys[]' versions.json); do
        echo "Processing $version/$variant ..."

        # Read values from JSON
        template=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].template // empty' versions.json)
        PG_MAJOR=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].PG_MAJOR // empty' versions.json)
        POSTGIS_MAJOR=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].POSTGIS_MAJOR // empty' versions.json)
        POSTGIS_VERSION=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].POSTGIS_VERSION // empty' versions.json)
        POSTGIS_SHA256=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].POSTGIS_SHA256 // empty' versions.json)
        BOOST_VERSION=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].BOOST_VERSION // empty' versions.json)
        POSTGIS_GIT_HASH=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].POSTGIS_GIT_HASH // empty' versions.json)
        CGAL_GIT_HASH=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].CGAL_GIT_HASH // empty' versions.json)
        SFCGAL_GIT_HASH=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].SFCGAL_GIT_HASH // empty' versions.json)
        PROJ_GIT_HASH=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].PROJ_GIT_HASH // empty' versions.json)
        GDAL_GIT_HASH=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].GDAL_GIT_HASH // empty' versions.json)
        GEOS_GIT_HASH=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].GEOS_GIT_HASH // empty' versions.json)
        tags=$(jq -r --arg v "$version" --arg var "$variant" '.[$v][$var].tags // empty' versions.json)

        if [ -z "$template" ]; then
            echo "  WARNING: No template specified for $version/$variant, skipping."
            continue
        fi

        if [ ! -f "$template" ]; then
            echo "  WARNING: Template '$template' not found, skipping."
            continue
        fi

        # Create directory
        dir="$version/$variant"
        mkdir -p "$dir"

        # Copy template to Dockerfile
        cp "$template" "$dir/Dockerfile"

        # Perform sed substitutions — only replace if the value is non-empty
        sed -i "s/%%TXT_AUTOGENERATED%%/${autogenerated}/g" "$dir/Dockerfile"

        if [ -n "$PG_MAJOR" ]; then
            sed -i "s/%%PG_MAJOR%%/${PG_MAJOR}/g" "$dir/Dockerfile"
        fi
        if [ -n "$POSTGIS_MAJOR" ]; then
            sed -i "s/%%POSTGIS_MAJOR%%/${POSTGIS_MAJOR}/g" "$dir/Dockerfile"
        fi
        if [ -n "$POSTGIS_VERSION" ]; then
            # POSTGIS_VERSION may contain + which is special in sed replacement
            sed -i "s/%%POSTGIS_VERSION%%/$(echo "$POSTGIS_VERSION" | sed 's/[&/\]/\\&/g')/g" "$dir/Dockerfile"
        fi
        if [ -n "$POSTGIS_SHA256" ]; then
            sed -i "s/%%POSTGIS_SHA256%%/${POSTGIS_SHA256}/g" "$dir/Dockerfile"
        fi

        # DEBIAN_VERSION — only for debian/master templates (not alpine)
        if [[ "$template" != *"alpine"* ]] && [ -n "$variant" ]; then
            sed -i "s/%%DEBIAN_VERSION%%/${variant}/g" "$dir/Dockerfile"
        fi

        if [ -n "$BOOST_VERSION" ]; then
            sed -i "s/%%BOOST_VERSION%%/${BOOST_VERSION}/g" "$dir/Dockerfile"
        fi
        if [ -n "$POSTGIS_GIT_HASH" ]; then
            sed -i "s/%%POSTGIS_GIT_HASH%%/${POSTGIS_GIT_HASH}/g" "$dir/Dockerfile"
        fi
        if [ -n "$CGAL_GIT_HASH" ]; then
            sed -i "s/%%CGAL_GIT_HASH%%/${CGAL_GIT_HASH}/g" "$dir/Dockerfile"
        fi
        if [ -n "$SFCGAL_GIT_HASH" ]; then
            sed -i "s/%%SFCGAL_GIT_HASH%%/${SFCGAL_GIT_HASH}/g" "$dir/Dockerfile"
        fi
        if [ -n "$PROJ_GIT_HASH" ]; then
            sed -i "s/%%PROJ_GIT_HASH%%/${PROJ_GIT_HASH}/g" "$dir/Dockerfile"
        fi
        if [ -n "$GDAL_GIT_HASH" ]; then
            sed -i "s/%%GDAL_GIT_HASH%%/${GDAL_GIT_HASH}/g" "$dir/Dockerfile"
        fi
        if [ -n "$GEOS_GIT_HASH" ]; then
            sed -i "s/%%GEOS_GIT_HASH%%/${GEOS_GIT_HASH}/g" "$dir/Dockerfile"
        fi

        # Copy helper scripts
        cp -p initdb-postgis.sh update-postgis.sh "$dir/"

        # Write tags file if tags are specified
        if [ -n "$tags" ]; then
            echo "$tags" > "$dir/tags"
        fi

        generated+=("$dir")
        echo "  -> Generated $dir/Dockerfile"
    done
done

echo ""
echo "============================="
echo "  apply-templates.sh summary"
echo "============================="
echo "Generated ${#generated[@]} Dockerfile(s):"
for g in "${generated[@]}"; do
    echo "  - $g/Dockerfile"
done
